### ISSUE TITLE
Can not use generateStaticParams with next/headers in Next.js 13

### ISSUE THREAD

**Issue by myl7** [myl7/mylmoe#25]
The error message is: Dynamic server usage: headers

Related: vercel/next.js#43427 vercel/next.js#43392 #24

Currently comment the headers() call to fix

**Comment by myl7** [comment]
Related vercel/next.js#44764

**Comment by subhasish-smiles** [comment]
In my next js 13 app dir project it was working fine with next-auth. But after adding middleware it shows me this error. I added the middleware file to do a custom i18n solution. I'm doing `req.headers.get('Accept-Language')` to get this header.

**Comment by milovangudelj** [comment]
Same for me. I'm using `next-auth` on my website and while trying to implement the new [i18n example](https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing) I got this error

**Dynamic server usage: headers**
```ts
app/[lang]/layout.tsx (96:39) @ getServerSession

  94 | 	};
  95 | }) {
> 96 | 	const session = await getServerSession();
     | 	                                     ^
```
In the console this message pops up
```shell
- warn Entire page /[lang] deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /[lang]
```

**Comment by milovangudelj** [comment]
Oh, sorry!
I totally missed that this was not an issue on the Next.js repo... :see_no_evil:

I'll post this there if I don't find a solution.

**Comment by myl7** [comment]
To leave from Next.js and go to Astro
